# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-17 22:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField()),
                ('due_on', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('note', 'Note')], max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('settled', models.BooleanField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_average_before', models.FloatField()),
                ('category_average_after', models.FloatField()),
                ('attendance_dates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(choices=[('missing', 'Missing Assignments delta'), ('category', 'Category delta'), ('attendance', 'Attendance delta')], max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingAssignmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Assignment')),
                ('delta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deltas.Delta')),
            ],
        ),
        migrations.AddField(
            model_name='delta',
            name='missing_assignments',
            field=models.ManyToManyField(through='deltas.MissingAssignmentRecord', to='sis_pull.Assignment'),
        ),
        migrations.AddField(
            model_name='delta',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Score'),
        ),
        migrations.AddField(
            model_name='delta',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
        migrations.AddField(
            model_name='action',
            name='deltas',
            field=models.ManyToManyField(to='deltas.Delta'),
        ),
        migrations.AddField(
            model_name='action',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
    ]
