# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 17:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('deltas', '0002_auto_20181023_1626'), ('deltas', '0003_auto_20181023_1627'), ('deltas', '0004_auto_20181023_1638'), ('deltas', '0005_auto_20181023_1649'), ('deltas', '0006_auto_20181023_1653'), ('deltas', '0007_auto_20181023_1709')]

    dependencies = [
        ('deltas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='completed_on',
        ),
        migrations.AlterField(
            model_name='action',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delta',
            name='attendance_dates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='due_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('note', 'Note')], default='note', max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('note', 'Note')], default='note', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('note', 'Note')], default='note', max_length=255),
        ),
    ]
