# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0002_auto_20181023_1626_squashed_0007_auto_20181023_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
