# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0003_auto_20181023_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='settled',
        ),
        migrations.AddField(
            model_name='action',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delta',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
