# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
        ('deltas', '0004_auto_20181023_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
            preserve_default=False,
        ),
    ]
