# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-31 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0005_action_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='category_average_after',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='category_average_before',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Score'),
        ),
    ]
