# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0005_action_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='deltas',
            field=models.ManyToManyField(blank=True, to='deltas.Delta'),
        ),
        migrations.AlterField(
            model_name='action',
            name='due_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('message', 'Message')], default='note', max_length=255),
        ),
    ]
