# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-01 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
        ('deltas', '0006_auto_20181031_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingassignmentrecord',
            name='new',
        ),
        migrations.AddField(
            model_name='delta',
            name='gradebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook'),
        ),
        migrations.AddField(
            model_name='missingassignmentrecord',
            name='missing_on',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 4, 42, 37, 824811)),
            preserve_default=False,
        ),
    ]
