# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-01 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0006_auto_20181031_2150'),
        ('deltas', '0007_auto_20181101_0442'),
    ]

    operations = [
    ]
