# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
        ('deltas', '0008_merge_20181101_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGradeContextRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('total_points_possible', models.FloatField()),
                ('average_points_earned', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
                ('latest_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Score')),
            ],
        ),
        migrations.AddField(
            model_name='delta',
            name='context_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deltas.CategoryGradeContextRecord'),
        ),
    ]
