# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-02 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0009_auto_20181102_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygradecontextrecord',
            name='timestamp',
        ),
    ]
