# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-06 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
        ('deltas', '0010_remove_categorygradecontextrecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygradecontextrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 6, 4, 43, 3, 566420)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='categorygradecontextrecord',
            name='gradebook',
        ),
        migrations.RemoveField(
            model_name='categorygradecontextrecord',
            name='latest_score',
        ),
        migrations.AlterUniqueTogether(
            name='categorygradecontextrecord',
            unique_together=set([('category', 'date')]),
        ),
    ]
