# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0014_auto_20181106_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.ScoreCache'),
        ),
    ]
