# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltas', '0015_auto_20181106_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delta',
            old_name='score',
            new_name='score_cache',
        ),
    ]
