# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0018_auto_20181129_0317'),
        ('deltas', '0017_remove_delta_attendance_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='score_cache',
        ),
        migrations.AddField(
            model_name='delta',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.Score'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.UserProfile'),
        ),
        migrations.AlterField(
            model_name='action',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Student'),
        ),
        migrations.AlterField(
            model_name='categorygradecontextrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Category'),
        ),
        migrations.AlterField(
            model_name='delta',
            name='gradebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.Gradebook'),
        ),
        migrations.AlterField(
            model_name='delta',
            name='missing_assignments',
            field=models.ManyToManyField(through='deltas.MissingAssignmentRecord', to='clarify.Assignment'),
        ),
        migrations.AlterField(
            model_name='delta',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Student'),
        ),
        migrations.AlterField(
            model_name='missingassignmentrecord',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Assignment'),
        ),
    ]
