# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('possible_points', models.FloatField()),
                ('possible_score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flag', models.CharField(choices=[('P', 'Present'), ('T', 'Tardy'), ('TE', 'Tardy Excused'), ('TU', 'Tardy Unexcused'), ('A', 'Absent'), ('AE', 'Absent Excused'), ('AU', 'Absent Unexcused')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('is_excused', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.GradeLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffSectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('primary_teacher', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(blank=True, max_length=50)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('prefix', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clarify.UserModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('clarify.usermodel',),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Term'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Student'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Section'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Section'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Student'),
        ),
        migrations.AddField(
            model_name='dailyattendancenode',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Student'),
        ),
        migrations.AddField(
            model_name='category',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Gradebook'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Category'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Gradebook'),
        ),
        migrations.AddField(
            model_name='staffsectionrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Staff'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='owners',
            field=models.ManyToManyField(to='clarify.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancenode',
            unique_together=set([('date', 'student')]),
        ),
    ]
