# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('DA', 'District Admin'), ('SA', 'School Admin'), ('T', 'Teacher')], default='T', max_length=3),
        ),
    ]
