# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-13 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clarify', '0003_auto_20181112_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clever_id', models.CharField(max_length=50, null=True, unique=True)),
                ('sis_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('prefix', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staff',
            name='usermodel_ptr',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffsectionrecord',
            name='staff',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.Category'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='owners',
            field=models.ManyToManyField(to='clarify.UserProfile'),
        ),
        migrations.AlterField(
            model_name='section',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='clever_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='staffsectionrecord',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clarify.UserProfile'),
            preserve_default=False,
        ),
    ]
