# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0005_auto_20181113_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsectionrecord',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
