# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0008_score_sis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
