# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-14 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0009_auto_20181114_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('student', 'assignment')]),
        ),
    ]
