# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0011_auto_20181114_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleverCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clever_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clevercode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.UserProfile'),
        ),
    ]
