# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-28 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0013_auto_20181127_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAdminRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.Term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarify.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='staffsectionrecord',
            unique_together=set([('user', 'section', 'start_date', 'end_date')]),
        ),
    ]
