# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-28 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0014_auto_20181128_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffsectionrecord',
            unique_together=set([('user', 'section')]),
        ),
    ]
