# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-29 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0015_auto_20181128_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffsectionrecord',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentrecord',
            unique_together=set([('student', 'section')]),
        ),
        migrations.AlterUniqueTogether(
            name='staffsectionrecord',
            unique_together=set([('user_profile', 'section')]),
        ),
    ]
