# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-29 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0017_auto_20181129_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clevercode',
            old_name='user',
            new_name='user_profile',
        ),
    ]
