# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0018_auto_20181129_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
