# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0020_assignment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='updated_on',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='score',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
