# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-07 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0020_assignment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
