# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-11 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0021_auto_20181207_2259'),
        ('clarify', '0021_remove_student_name'),
    ]

    operations = [
    ]
