# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0024_auto_20181211_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
