# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarify', '0026_auto_20181220_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleverAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, unique=True)),
                ('clever_token', models.CharField(blank=True, max_length=300, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('reset_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CleverCode',
            new_name='GoogleAuth',
        ),
        migrations.RenameField(
            model_name='googleauth',
            old_name='code',
            new_name='google_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='clever_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_token_expiry',
        ),
        migrations.AddField(
            model_name='section',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.GoogleAuth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cleverauth',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clever_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clarify.CleverAuth'),
        ),
    ]
