# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sis_pull.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_code', models.CharField(blank=True, max_length=30)),
                ('flag_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryScoreCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_points', models.FloatField()),
                ('points_earned', models.FloatField()),
                ('percentage', models.FloatField()),
                ('category_name', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
                ('assignment_count', models.IntegerField()),
                ('calculated_at', models.DateTimeField()),
                ('timeframe_start_date', models.DateField()),
                ('timeframe_end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('long_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('school_course_id', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('gradebook_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('academic_year', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradebookSectionCourseAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Course')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('short_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=455, null=True)),
            ],
            bases=(sis_pull.models.GetCurrentStudentsMixin, sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OverallScoreCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_points', models.FloatField(null=True)),
                ('points_earned', models.FloatField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('mark', models.CharField(max_length=255, null=True)),
                ('missing_count', models.IntegerField(null=True)),
                ('zero_count', models.IntegerField(null=True)),
                ('excused_count', models.IntegerField(null=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, null=True)),
            ],
            bases=(sis_pull.models.GetCurrentStudentsMixin, sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionLevelRosterPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('entry_date', models.DateField(null=True)),
                ('leave_date', models.DateField(null=True)),
                ('is_primary_teacher', models.NullBooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Course')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradeLevel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_type_id', models.IntegerField(choices=[(1, 'Middle and K-8 Schools'), (2, 'High Schools'), (3, 'Continuation schools'), (4, 'Pre-schools'), (5, 'Adult Education Facilities'), (6, 'Special Education Facilities'), (7, 'Other Schools and Facilities'), (9, 'Elementary Schools'), (10, 'Closed')])),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone1', models.CharField(max_length=100, null=True)),
                ('phone2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('end_grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_grade_level', to='sis_pull.GradeLevel')),
                ('start_grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_grade_level', to='sis_pull.GradeLevel')),
            ],
            bases=(sis_pull.models.GetCurrentStudentsMixin, sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], default='MS', max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.IntegerField(choices=[(146, 'Refused to Identify'), (141, 'Filipino'), (144, 'White'), (134, 'Other Asian'), (133, 'Cambodian'), (132, 'Laotian'), (131, 'Asian Indian'), (130, 'Vietnamese'), (129, 'Korean'), (128, 'Japanese'), (127, 'Chinese'), (145, 'Hmong'), (125, 'American Indian Or Alaska Native'), (140, 'Other Pacific Islander'), (139, 'Tahitian'), (138, 'Samoan'), (137, 'Guamanian'), (136, 'Hawaiian'), (143, 'Black or African American')], null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
        ),
        migrations.AddField(
            model_name='overallscorecache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
        migrations.AddField(
            model_name='gradebooksectioncourseaffinity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section'),
        ),
        migrations.AddField(
            model_name='gradebooksectioncourseaffinity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
        ),
        migrations.AddField(
            model_name='categoryscorecache',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook'),
        ),
        migrations.AddField(
            model_name='categoryscorecache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
        migrations.AddField(
            model_name='category',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook'),
        ),
        migrations.AddField(
            model_name='attendancedailyrecord',
            name='attendance_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.AttendanceFlag'),
        ),
        migrations.AddField(
            model_name='attendancedailyrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
        ),
        migrations.AddField(
            model_name='attendancedailyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
    ]
