# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('date', models.DateField()),
                ('attendance_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.AttendanceFlag')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
