# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sis_pull.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('role_level', models.IntegerField(blank=True, null=True)),
                ('can_teach', models.BooleanField()),
                ('can_counsel', models.BooleanField()),
                ('job_classification_id', models.IntegerField(blank=True, null=True)),
                ('role_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('can_refer_discipline', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('schedule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_mod_time', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.NullBooleanField()),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Schedule')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_key', models.CharField(max_length=255)),
                ('code_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('state_num', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.NullBooleanField()),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('linkable', models.NullBooleanField()),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('custom_code', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_standard_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Standard')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StandardsCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('points_earned', models.FloatField(blank=True, null=True)),
                ('possible_points', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('missing_count', models.IntegerField(blank=True, null=True)),
                ('assignment_count', models.IntegerField(blank=True, null=True)),
                ('zero_count', models.IntegerField(blank=True, null=True)),
                ('excused_count', models.IntegerField(blank=True, null=True)),
                ('timeframe_start_date', models.DateField()),
                ('timeframe_end_date', models.DateField()),
                ('calculated_at', models.DateTimeField()),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=225, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.NullBooleanField()),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.NullBooleanField()),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.State')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term_num', models.IntegerField()),
                ('term_type', models.IntegerField()),
                ('local_term_id', models.IntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Schedule')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Session')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserTermRoleAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_schedule_id', models.IntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Role')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.AddField(
            model_name='overallscorecache',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Subject'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.SessionType'),
        ),
        migrations.AddField(
            model_name='session',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
        ),
    ]
