# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sis_pull.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTimeblockAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Timeblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeblock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_num', models.IntegerField()),
                ('is_homeroom', models.NullBooleanField()),
                ('occurrence_order', models.SmallIntegerField()),
                ('is_primary', models.BooleanField()),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sectiontimeblockaffinity',
            name='timeblock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Timeblock'),
        ),
    ]
