# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradebookSectionCourseAff',
            new_name='GradebookSectionCourseAffinity',
        ),
        migrations.AddField(
            model_name='attendancedailyrecord',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='end_grade_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_grade_level', to='sis_pull.GradeLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='phone1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='phone2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='site_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.IntegerField(choices=[(1, 'Middle and K-8 Schools'), (2, 'High Schools'), (3, 'Continuation schools'), (4, 'Pre-schools'), (5, 'Adult Education Facilities'), (6, 'Special Education Facilities'), (7, 'Other Schools and Facilities'), (9, 'Elementary Schools'), (10, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='start_grade_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_grade_level', to='sis_pull.GradeLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='zip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancedailyrecord',
            name='attendance_flag',
            field=models.CharField(choices=[('X', 'Not Enrolled'), ('N', 'School Closed'), ('+', 'Present'), ('L', 'Excused tardy'), ('M', 'Unexcused Tardy'), ('R', 'Early Release'), ('E', 'Excused'), ('T', 'Tardy'), ('U', 'Unexcused'), ('Y', 'T30'), ('I', 'Independent Study Complete'), ('-', 'Independent Study Pending'), ('_', 'Independent Study NOT-Complete'), ('A', 'Absent'), ('D', 'Delete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=models.IntegerField(choices=[(146, 'Refused to Identify'), (141, 'Filipino'), (144, 'White'), (134, 'Other Asian'), (133, 'Cambodian'), (132, 'Laotian'), (131, 'Asian Indian'), (130, 'Vietnamese'), (129, 'Korean'), (128, 'Japanese'), (127, 'Chinese'), (145, 'Hmong'), (125, 'American Indian Or Alaska Native'), (140, 'Other Pacific Islander'), (139, 'Tahitian'), (138, 'Samoan'), (137, 'Guamanian'), (136, 'Hawaiian'), (143, 'Black or African American')]),
        ),
        migrations.DeleteModel(
            name='AttendanceFlag',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
    ]
