# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0002_attendancedailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallscorecache',
            name='excused_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='missing_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='points_earned',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='possible_points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='zero_count',
            field=models.IntegerField(null=True),
        ),
    ]
