# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0002_auto_20180416_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedailyrecord',
            name='attendance_flag',
            field=models.IntegerField(choices=[(1, 'Not Enrolled'), (2, 'School Closed'), (4, 'Present'), (10, 'Excused tardy'), (11, 'Unexcused Tardy'), (9, 'Early Release'), (7, 'Excused'), (5, 'Tardy'), (8, 'Unexcused'), (12, 'T30'), (13, 'Independent Study Complete'), (14, 'Independent Study Pending'), (15, 'Independent Study NOT-Complete'), (6, 'Absent'), (3, 'Delete')]),
        ),
    ]
