# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0003_auto_20180418_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallscorecache',
            name='mark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
