# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0003_auto_20180522_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryscorecache',
            name='assignment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='points_earned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='possible_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='timeframe_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='timeframe_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
