# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180418_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
