# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180522_0433'),
        ('sis_pull', '0002_auto_20180522_1700'),
    ]

    operations = [
    ]
