# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180417_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
