# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180418_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradeLevel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student')),
            ],
        ),
    ]
