# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180418_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallscorecache',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
