# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0005_auto_20180515_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Course', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradeLevel', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff', to_field='source_object_id'),
        ),
    ]
