# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0005_overallscorecache_calculated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
