# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0005_merge_20180607_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryscorecache',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
