# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0005_auto_20180417_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
