# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0006_auto_20180607_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryscorecache',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category'),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='gradebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook'),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
        ),
    ]
