# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0006_auto_20180417_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='is_primary_teacher',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='leave_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sectionlevelrosterperyear',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student'),
            preserve_default=False,
        ),
    ]
