# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0006_auto_20180516_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlevelrosterperyear',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site', to_field='source_object_id'),
        ),
    ]
