# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0007_auto_20180417_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionlevelrosterperyear',
            old_name='student_id',
            new_name='student',
        ),
    ]
