# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0007_auto_20180607_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradeLevel')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student')),
            ],
        ),
    ]
