# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0007_auto_20180516_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedailyrecord',
            name='attendance_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.AttendanceFlag', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='attendancedailyrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='attendancedailyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='categoryscorecache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Course', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='gradebooksectioncourseaffinity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='overallscorecache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='site',
            name='end_grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_grade_level', to='sis_pull.GradeLevel', to_field='source_object_id'),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_grade_level', to='sis_pull.GradeLevel', to_field='source_object_id'),
        ),
    ]
