# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0008_auto_20180516_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='site_id',
            new_name='site',
        ),
    ]
