# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0008_currentroster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentroster',
            old_name='grade_level_id',
            new_name='grade_level',
        ),
        migrations.RenameField(
            model_name='currentroster',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='currentroster',
            old_name='student_id',
            new_name='student',
        ),
    ]
