# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0009_auto_20180607_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='site',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='parent_standard_id',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='standardscache',
            name='gradebook',
        ),
        migrations.RemoveField(
            model_name='standardscache',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='standardscache',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='state',
        ),
        migrations.RemoveField(
            model_name='term',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='term',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usertermroleaffinity',
            name='role',
        ),
        migrations.RemoveField(
            model_name='usertermroleaffinity',
            name='term',
        ),
        migrations.RemoveField(
            model_name='usertermroleaffinity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionType',
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
        migrations.DeleteModel(
            name='StandardsCache',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='UserTermRoleAffinity',
        ),
    ]
