# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0009_auto_20180516_1508'),
        ('sis_pull', '0006_auto_20180503_1854'),
    ]

    operations = [
    ]
