# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0009_auto_20180417_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_course_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
