# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0010_merge_20180518_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('role_name', models.CharField(max_length=255)),
                ('role_level', models.IntegerField(blank=True, null=True)),
                ('can_teach', models.BooleanField()),
                ('can_counsel', models.BooleanField()),
                ('job_classification_id', models.IntegerField(blank=True, null=True)),
                ('role_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('can_refer_discipline', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('schedule_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_mod_time', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('academic_year', models.IntegerField()),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Schedule', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('code_key', models.CharField(max_length=255)),
                ('code_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('term_name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term_num', models.IntegerField()),
                ('term_type', models.IntegerField()),
                ('local_term_id', models.IntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Schedule', to_field='source_object_id')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Session', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTermRoleAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('last_schedule_id', models.IntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Role', to_field='source_object_id')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Term', to_field='source_object_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.SessionType', to_field='source_object_id'),
        ),
        migrations.AddField(
            model_name='session',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site', to_field='source_object_id'),
        ),
    ]
