# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0010_auto_20180608_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryscorecache',
            name='excused_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryscorecache',
            name='missing_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryscorecache',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryscorecache',
            name='zero_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
