# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0011_auto_20180608_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=24)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assign_date', models.DateField()),
                ('due_date', models.DateField()),
                ('possible_points', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('possible_score', models.FloatField(blank=True, null=True)),
                ('is_extra_credit', models.BooleanField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category')),
                ('gradebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGscaAff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Assignment')),
                ('gsca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradebookSectionCourseAffinity')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, null=True)),
                ('is_excused', models.NullBooleanField()),
                ('is_missing', models.NullBooleanField()),
                ('points', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('use_for_calc', models.NullBooleanField()),
                ('use_for_aggregate', models.NullBooleanField()),
                ('use_category_weights', models.NullBooleanField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Assignment')),
                ('gradebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student')),
            ],
        ),
    ]
