# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0011_auto_20180518_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('state_num', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.NullBooleanField()),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('linkable', models.NullBooleanField()),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('custom_code', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category', to_field='source_object_id')),
                ('parent_standard_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Standard', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardsCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('points_earned', models.FloatField(blank=True, null=True)),
                ('possible_points', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('missing_count', models.IntegerField(blank=True, null=True)),
                ('assignment_count', models.IntegerField(blank=True, null=True)),
                ('zero_count', models.IntegerField(blank=True, null=True)),
                ('excused_count', models.IntegerField(blank=True, null=True)),
                ('timeframe_start_date', models.DateField()),
                ('timeframe_end_date', models.DateField()),
                ('calculated_at', models.DateTimeField()),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Gradebook', to_field='source_object_id')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Standard', to_field='source_object_id')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Student', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('source_object_id', models.PositiveIntegerField(null=True, unique=True)),
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=225, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.NullBooleanField()),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.NullBooleanField()),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.State', to_field='source_object_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Subject', to_field='source_object_id'),
        ),
    ]
