# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0012_assignment_assignmentgscaaff_scorecache'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentGscaAff',
            new_name='AssignmentGscaAffinity',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
