# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0012_auto_20180518_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
