# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0013_auto_20180518_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='standard',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
