# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0013_auto_20180608_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecache',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Category'),
        ),
    ]
