# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0014_auto_20180608_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgscaaffinity',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentgscaaffinity',
            name='gsca',
        ),
        migrations.DeleteModel(
            name='AssignmentGscaAffinity',
        ),
    ]
