# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-09 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sis_pull.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sis_pull', '0015_auto_20180608_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('role_level', models.IntegerField(blank=True, null=True)),
                ('can_teach', models.BooleanField()),
                ('can_counsel', models.BooleanField()),
                ('job_classification_id', models.IntegerField(blank=True, null=True)),
                ('role_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('can_refer_discipline', models.BooleanField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_key', models.CharField(max_length=255)),
                ('code_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key', models.CharField(blank=True, max_length=255, null=True)),
                ('system_key_sort', models.IntegerField(blank=True, null=True)),
                ('state_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('system_state_id', models.IntegerField(blank=True, null=True)),
                ('system_key_translation', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term_num', models.IntegerField()),
                ('term_type', models.IntegerField()),
                ('local_term_id', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Session')),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserTermRoleAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Role')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.SessionType'),
        ),
        migrations.AddField(
            model_name='session',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Site'),
        ),
    ]
