# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0016_auto_20180609_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertermroleaffinity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
        ),
    ]
