# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0019_auto_20180710_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='has_students',
            field=models.NullBooleanField(),
        ),
    ]
