# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import sis_pull.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0020_site_has_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('gradebook_id', models.IntegerField()),
                ('is_excused', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('student_id', models.IntegerField()),
            ],
            bases=(sis_pull.models.SourceObjectMixin, models.Model),
        ),
    ]
