# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0022_auto_20181017_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period_name', models.CharField(max_length=200)),
                ('grading_window_start_date', models.DateField(blank=True, null=True)),
                ('grading_window_end_date', models.DateField(blank=True, null=True)),
                ('grading_period_start_date', models.DateField(blank=True, null=True)),
                ('grading_period_end_date', models.DateField(blank=True, null=True)),
                ('grading_window_start_date_overwrite', models.DateField(blank=True, null=True)),
                ('grading_window_end_date_overwrite', models.DateField(blank=True, null=True)),
                ('is_end_of_term', models.BooleanField()),
                ('is_k6_report_card', models.NullBooleanField()),
                ('disable_gpa', models.BooleanField()),
                ('grading_period_num', models.IntegerField(blank=True, null=True)),
                ('term_type', models.IntegerField(blank=True, null=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('report_card_snapshot_date', models.DateField(blank=True, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Term')),
            ],
        ),
        migrations.CreateModel(
            name='SectionGradingPeriodAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Course')),
                ('grading_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.GradingPeriod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTeacherAffinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_teacher', models.NullBooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('classroom_role_id', models.IntegerField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff')),
            ],
        ),
    ]
