# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_pull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('query', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('source_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Worksheet')),
            ],
        ),
        migrations.AddField(
            model_name='worksheet',
            name='reports',
            field=models.ManyToManyField(through='reports.WorksheetMembership', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='worksheetmembership',
            unique_together=set([('report', 'worksheet')]),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('staff', 'query')]),
        ),
    ]
