# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksheetmembership',
            unique_together=set([('report', 'worksheet')]),
        ),
    ]
