# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180503_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='worksheet',
            old_name='name',
            new_name='title',
        ),
    ]
