# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180710_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='source_report',
        ),
        migrations.AddField(
            model_name='reportshare',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='reportshare',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='reports.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='reportshare',
            unique_together=set([('parent', 'child')]),
        ),
    ]
