# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0004_auto_20180418_0100'),
        ('reports', '0003_auto_20180503_0538'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('staff', 'query')]),
        ),
    ]
