# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180715_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshare',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='reports.Report'),
        ),
    ]
