# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_pull', '0019_auto_20180710_1841'),
        ('reports', '0004_auto_20180715_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshare',
            name='by',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='sis_pull.Staff'),
            preserve_default=False,
        ),
    ]
