# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportshare_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='worksheetmembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='worksheetmembership',
            name='report',
        ),
        migrations.RemoveField(
            model_name='worksheetmembership',
            name='worksheet',
        ),
        migrations.DeleteModel(
            name='Worksheet',
        ),
        migrations.DeleteModel(
            name='WorksheetMembership',
        ),
    ]
