# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20180716_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportshare',
            old_name='by',
            new_name='shared_by',
        ),
    ]
