# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20180717_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshare',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
