# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportshare_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshare',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
