# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_mirror', '0002_roles_schedules_sessions_sessiontypes_usertermroleaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('standard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_standard_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('state_num', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.NullBooleanField()),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('linkable', models.NullBooleanField()),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('custom_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'standards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardsCache',
            fields=[
                ('cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('points_earned', models.FloatField(blank=True, null=True)),
                ('possible_points', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('missing_count', models.IntegerField(blank=True, null=True)),
                ('assignment_count', models.IntegerField(blank=True, null=True)),
                ('zero_count', models.IntegerField(blank=True, null=True)),
                ('excused_count', models.IntegerField(blank=True, null=True)),
                ('timeframe_start_date', models.DateField()),
                ('timeframe_end_date', models.DateField()),
                ('calculated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'standards_cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=225, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.NullBooleanField()),
                ('locale', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.NullBooleanField()),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
    ]
