# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_mirror', '0003_standards_standardscache_states_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGscaAff',
            fields=[
                ('aga_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assignment_gsca_aff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=24)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assign_date', models.DateField()),
                ('due_date', models.DateField()),
                ('possible_points', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('field_grading_period_id', models.IntegerField(blank=True, db_column='_grading_period_id', null=True)),
                ('auto_score_type', models.IntegerField(blank=True, null=True)),
                ('auto_score_id', models.IntegerField(blank=True, null=True)),
                ('possible_score', models.FloatField(blank=True, null=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_extra_credit', models.BooleanField()),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreCache',
            fields=[
                ('cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('is_excused', models.NullBooleanField()),
                ('is_missing', models.NullBooleanField()),
                ('points', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('use_for_calc', models.NullBooleanField()),
                ('use_for_aggregate', models.NullBooleanField()),
                ('use_category_weights', models.NullBooleanField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('gs_id', models.IntegerField(blank=True, null=True)),
                ('eva_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score_cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_ssa_id', models.IntegerField(blank=True, db_column='_ssa_id', null=True)),
                ('assignment_id', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('gradebook_id', models.IntegerField()),
                ('is_excused', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'scores',
                'managed': False,
            },
        ),
    ]
