# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_mirror', '0004_assignmentgscaaff_assignments_scorecache_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPeriods',
            fields=[
                ('grading_period_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grading_period_name', models.CharField(max_length=200)),
                ('grading_window_start_date', models.DateField(blank=True, null=True)),
                ('grading_window_end_date', models.DateField(blank=True, null=True)),
                ('grading_period_start_date', models.DateField(blank=True, null=True)),
                ('grading_period_end_date', models.DateField(blank=True, null=True)),
                ('grading_window_start_date_overwrite', models.DateField(blank=True, null=True)),
                ('grading_window_end_date_overwrite', models.DateField(blank=True, null=True)),
                ('is_end_of_term', models.BooleanField()),
                ('is_k6_report_card', models.NullBooleanField()),
                ('disable_gpa', models.BooleanField()),
                ('grading_period_num', models.IntegerField(blank=True, null=True)),
                ('term_type', models.IntegerField(blank=True, null=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('report_card_snapshot_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grading_periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionGradingPeriodAff',
            fields=[
                ('sgpa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_published', models.BooleanField()),
            ],
            options={
                'db_table': 'section_grading_period_aff',
                'managed': False,
            },
        ),
    ]
