# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_mirror', '0005_gradingperiods_sectiongradingperiodaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGradeLevels',
            fields=[
                ('cgl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('required', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_grade_levels',
                'managed': False,
            },
        ),
    ]
