# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sis_mirror.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_mirror', '0006_coursegradelevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSectionTeacherAffDates',
            fields=[
                ('sta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sis_mirror.SectionTeacherAff')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='sis_mirror.Sections')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='sis_mirror.Schedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='sis_mirror.Users')),
                ('primary_teacher', models.NullBooleanField()),
                ('highly_qualified_teacher', models.CharField(blank=True, max_length=1, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule_section_teacher_aff_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionTeacherAffDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_teacher', models.NullBooleanField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section_teacher_aff_dates',
                'managed': False,
            },
            bases=(sis_mirror.models.TeacherSectionsMixin, models.Model),
        ),
    ]
